name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  deploy-dev:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Assemble debug with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: assembleDebug
        env:
          username: ${{ secrets.ORGANIZATION_PACKAGES_ACTOR }}
          password: ${{ secrets.ORGANIZATION_PACKAGES_TOKEN }}
      - name: Setup key
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_DEV_KEY }}" >  "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
      - name: Deploy dev
        run: |
          cd ./app/build/outputs/apk/debug && rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . looyou@looyou.online:/home/looyou/android